accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^$', views.loginview, name='login'),
    url(r'^accounts/login/$', views.loginview),
    url(r'^accounts/authview/$', views.authview, name='authview'),
    url(r'^accounts/logout/$', views.logoutview, name='logoutview'),
    url(r'^accounts/loggedin/$', views.loggedin, name='loggedin'),
    url(r'^accounts/invalid/$', views.invalid, name='invalid_login'),
    url(r'^accounts/register/$', views.register_user, name='register_user'),
    url(r'^accounts/register_success/$', views.register_success, name='register_success'),
]

guarantordoc/urls.py
from django.conf.urls import url
from . import views

app_name = 'gaurantordoc'

urlpatterns = [
    url(r'^guarantorslist/$', views.index, name='index'),
    url(r'^guarantor/$', views.ping, name='ping'),
    url(r'^guarantors/$', views.ping, name='ping'),
    url(r'^accesstoken/$', views.gettoken, name='gettoken'),
    url(r'^send/guarantordoc/$', views.sendguarantordoc, name='sendguarantordoc'),
    url(r'^generatepdf/$', views.html_to_pdf_view, name='guarantorpdf'),
    url(r'^psearch/(?P<guarantorid>[a-zA-Z0-9_]+?)/$', views.html_to_pdf_view, name='psearch'),
    # url(r'^(?P<book_id>[a-zA-Z0-9_]+)/$', views., name='detail'),
    # url(r'^preview/(?P<book_id>[a-zA-Z0-9_].+?)/$', views.pdetail, name='pdetail'),
    # url(r'^searchedkeyword/(?P<searched_keyword>[a-zA-Z0-9_].+?)/$', views.psearch, name='psearch'),
    # url(r'^ajax/downloadbook/$', views.downloadbook, name='downloadbook'),
    # url(r'^ajax/watchedVideos/$', views.watchedVideos, name='watchedVideos'),
]

moove_doc_signing/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^guarantordoc/', include('guarantordoc.urls')),
    url(r'^', include('guarantordoc.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^', include('accounts.urls')),
    # url(r'^search/', include('search.urls')),
    # url(r'^', include('search.urls')),
]

guarantordoc/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from .models import Guarantordetails, Applications, GuarantorLists, Guarantortosign
from django.shortcuts import render, get_object_or_404, redirect 
from django.http import HttpResponseRedirect, Http404, HttpResponse, JsonResponse
from django.core.paginator import Paginator
from django.contrib import messages
from django.db.models import F
from pprint import pprint
import requests
import json
from django_datatables_view.base_datatable_view import BaseDatatableView
from django.utils.html import escape
from django.core.files.storage import FileSystemStorage
from django.template.loader import render_to_string
from weasyprint import HTML


def ping(request):
    return HttpResponse("00")

def index(request):
    guarantorlist = GuarantorLists.objects.raw('''SELECT b.ID, b.drn, b.lastname, b.firstname, b.phone, b.email, b.guarantorid, b.address, CONCAT(c.firstname, ' ', c.surname) AS drivername, d.requestid FROM guarantordetails b join applications c on b.DRN = c.DRN left join guarantortosign d on b.ID = d.guarantorid''')
    context = {
        'title': 'Welcome',
        'guarantorlist': guarantorlist,
    }
    return render(request, 'guarantordoc/index.html', context) 
    # return HttpResponse(guarantorlist)

def createDocument(fileList,Oauthtoken,guarantorname, guarantoremail):
    headers = {'Authorization':'Zoho-oauthtoken '+Oauthtoken}
    files =[]
    fs = FileSystemStorage('guarantordoc/unsigneddoc/')
    for i in fileList:
        files.append(('file', (i[0],fs.open(i[0]),i[2])))
    req_data={}
    req_data['request_name']=guarantorname
    req_data["expiration_days"]= 10
    req_data["is_sequential"]=True
    req_data["email_reminders"]=True
    req_data["reminder_period"]= 5
    actions_list=[]
    actions_list.append({"recipient_name":guarantorname,"recipient_email":guarantoremail,"action_type":"SIGN","private_notes":"Please get back to us for further queries","signing_order":0,"verify_recipient":False})
    req_data['actions']=actions_list
    data={}
    data['requests']=req_data
    data_json={}
    data_json['data'] = json.dumps(data)
    r = requests.post('https://sign.zoho.com/api/v1/requests', files=files, data=data_json,headers=headers)
    return r.json()
    
def submitDocument(request_id,respjson,Oauthtoken):
    headers = {'Authorization':'Zoho-oauthtoken '+Oauthtoken}
    req_data={}
    req_data['request_name']=respjson['request_name']
    docIdsJsonArray = respjson['document_ids']
    actionsJsonArray = respjson['actions']
    for i in docIdsJsonArray:
        docId=i["document_id"]      
        for j in actionsJsonArray:
            fields=[]
            sigField={}
            sigField["field_type_name"]= "Signature"
            sigField["is_mandatory"]= True
            sigField["field_name"]= "Signature"
            sigField["page_no"]= 0
            sigField["y_coord"]= 300
            sigField["abs_width"]= 305
            sigField["description_tooltip"]= ""
            sigField["x_coord"]= 60
            sigField["abs_height"]= 60
            sigField["document_id"]= docId
            fields.append(sigField)
            # emailField={}
            # emailField["field_type_name"]= "Textfield"
            # emailField["text_property"]={}
            # emailField["text_property"]["is_italic"]= False
            # emailField["text_property"]["is_underline"]= False
            # emailField["text_property"]["font_color"]= "000000"
            # emailField["text_property"]["font_size"]= 12
            # emailField["text_property"]["is_read_only"]= False
            # emailField["text_property"]["is_bold"]= False
            # emailField["text_property"]["font"]= "Arial"
            # emailField["is_mandatory"]= True
            # emailField["page_no"]= 0
            # emailField["document_id"]= docId
            # emailField["field_name"]= "In Year"
            # emailField["y_coord"]= 195
            # emailField["abs_width"]= 45
            # emailField["description_tooltip"]= ""
            # emailField["x_coord"]=350
            # emailField["abs_height"]= 16
            # fields.append(emailField)
            if 'fields' in j:
                j['fields']=j['fields']+fields
            else:
                j["fields"]=fields
            j.pop('is_bulk',None)
            j.pop('allow_signing',None)
            j.pop('action_status',None)
    req_data['actions']=actionsJsonArray
    data={}
    data['requests']=req_data
    data_json={}
    data_json['data'] = json.dumps(data)
    url = 'https://sign.zoho.com/api/v1/requests/'+request_id+'/submit'
    r = requests.post(url, files=[],data=data_json, headers=headers)
    return r.json()


def html_to_pdf_view(request, guarantorid):
    try:
        guarantor = Guarantordetails.objects.filter(id=guarantorid).only("firstname", "lastname","middlename", "phone", "email", "drn").first()
        driverdrn = guarantor.drn
        driver = Applications.objects.filter(drn=driverdrn).only("firstname", "surname","middlename", "mobile", "email", "drn").first()
        guarantorname = guarantor.firstname +" "+guarantor.lastname
        guarantoremail = guarantor.email
        
        docname = guarantor.firstname +""+guarantor.middlename+""+guarantor.lastname
        drivername = driver.firstname +" "+driver.middlename+" "+driver.surname
        
        html_string = render_to_string('guarantordoc/pdf_template.html', {'guarantorname': guarantorname, 'drivername': drivername})

        html = HTML(string=html_string)
        html.write_pdf(target='guarantordoc/unsigneddoc/'+docname+'.pdf');

        # return response
        # tokenjson = gettoken()
        refreshtokenjson = getrefreshtoken()
        
        Oauthtoken = refreshtokenjson['access_token']

        file_list=[[docname+".pdf","guarantordoc/unsigneddoc/","application/pdf"]]
        respjson= createDocument(file_list,Oauthtoken, guarantorname, guarantoremail)

        respjson=respjson['requests']
        request_id=respjson['request_id']
        submitrespjson=submitDocument(request_id,respjson,Oauthtoken)
        finalresp=submitrespjson['message']
        finalrespstatus=submitrespjson['status']
        # frequest_id=submitrespjson['request_id']

        guatosigndoc = Guarantortosign()
        guatosigndoc.guarantorid = guarantorid
        guatosigndoc.requestid = request_id
        guatosigndoc.status = "Pending"
        guatosigndoc.save()
        # fdocument_id=finalresp['document_ids']
        # return HttpResponse(finalresp)

        messages.success(request, finalresp+" to "+guarantorname)
        return HttpResponseRedirect('/guarantorslist/')
    except requests.exceptions.ConnectionError:
        connection_status = "Connection refused"
        context = {
            'exception': connection_status,
        }
        # return HttpResponse(requests.exceptions)
        messages.warning(request, connection_status)
        return HttpResponseRedirect('/guarantorslist/')
    except AssertionError as error:
        # Output expected AssertionErrors.
        # Logging.log_exception(error)
        context = {
            'exception': "Request Not found",
        }
        # return HttpResponse(error)
        messages.warning(request, error)
        return HttpResponseRedirect('/guarantorslist/')
    except Exception as exception:
        # Output unexpected Exceptions.
        # Logging.log_exception(exception, False)
        context = {
            'exception': "Request Not found",
        }
        # return HttpResponse(exception)
        messages.warning(request, exception)
        return HttpResponseRedirect('/guarantorslist/')

def gettoken_test(request):
    try:
        getresponse = requests.post('https://accounts.zoho.com/oauth/v2/token?refresh_token=1000.68e0e4370bdb84fc2b365aeff4c5fc65.d3dc0277456dddcb2df9ca8297d894ba&client_id=1000.2O5WF7FXABOWF8TRT4NVZ4GTDAUGOO&client_secret=6783e2b027b6c880b7dca0fe7a8d3762345ec76674&redirect_uri=http://127.0.0.1:8000/guarantors&grant_type=refresh_token')
        return HttpResponse(getresponse)
    except Exception as exception:
        context = {
            'exception': "Request Not found",
        }
        return HttpResponse(exception)

    
def gettoken():
    try:
        getresponse = requests.post('https://accounts.zoho.com/oauth/v2/token?code=1000.7f275cda053cc314d6d2353736087085.c542ce20f645dc531686d5fade9425e3&client_id=1000.61DFAE1NE31HICJJZC06O3EPY08W0V&client_secret=840dc61b265a5e413e2091d47c461a3af4324b314d&redirect_uri=https://guarantor.moove.africa/guarantors&grant_type=authorization_code')
        return getresponse.json()
    except Exception as exception:
        context = {
            'exception': "Request Not found",
        }
        return HttpResponse(exception)

def getrefreshtoken_test():
    try:
        getrefreshresponse = requests.post('https://accounts.zoho.com/oauth/v2/token?refresh_token=1000.68e0e4370bdb84fc2b365aeff4c5fc65.d3dc0277456dddcb2df9ca8297d894ba&client_id=1000.2O5WF7FXABOWF8TRT4NVZ4GTDAUGOO&client_secret=6783e2b027b6c880b7dca0fe7a8d3762345ec76674&redirect_uri=http://127.0.0.1:8000/guarantors&grant_type=refresh_token')
        return getrefreshresponse.json()
    except Exception as exception:
        context = {
            'exception': "Request Not found",
        }
        return HttpResponse(exception)

def getrefreshtoken():
    try:
        getrefreshresponse = requests.post('https://accounts.zoho.com/oauth/v2/token?refresh_token=1000.66fa270f2209b968a21f837ad243e0bd.41db074f2b1e3ab9b3f688bc056a2a5e&client_id=1000.61DFAE1NE31HICJJZC06O3EPY08W0V&client_secret=840dc61b265a5e413e2091d47c461a3af4324b314d&redirect_uri=https://guarantor.moove.africa/guarantors&grant_type=refresh_token')
        return getrefreshresponse.json()
    except Exception as exception:
        context = {
            'exception': "Request Not found",
        }
        return HttpResponse(exception)

guarantordoc/templates/guarantordoc/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %} Title {% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'guarantordoc/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'guarantordoc/css/all.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'guarantordoc/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'guarantordoc/css/jquery.dataTables.css' %}">
    <script type="text/javascript" src="{% static 'guarantordoc/js/jquery-3.3.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'guarantordoc/js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'guarantordoc/js/all.js' %}"></script>
    <script type="text/javascript" src="{% static 'guarantordoc/js/sweetalert.min.js' %}"></script>
</head>
<body>
    {% block body%} {% endblock %}
</body>
<script type="text/javascript" src="{% static 'guarantordoc/js/jquery.dataTables.js' %}"></script>
<script type ="text/javascript">
    $(document).ready(function(){
        $('#etable').DataTable();
        $(".overlay").hide();
        $(document).on("click", ".sendBtn", function(){
            $(".overlay").show();
            var guarantordrn = $(this).attr("data-guarantordrn");
            guarantorid = $(this).attr("data-guarantorid");
            console.log(guarantordrn);
            swal({
                title: "Are you sure?",
                text: "You want to send document to "+ guarantordrn +" for signing", 
                icon: "warning",
                content: {
                    element: "input",
                    attributes: {
                      placeholder: "type proceed to continue",
                      type: "text",
                    },
                },
                showCancelButton: true
            })
            .then((inputValue) => {
                $(".overlay").hide();

                if (inputValue === "") {
                    swal("Error!", "You need to type the proceed to continue");
                    $(".overlay").hide();
                    return false;
                }else if(inputValue === "proceed"){
                    $(".overlay").show();
                    var url = "{% url 'gaurantordoc:psearch' guarantorid='gdid' %}";  // 'test' is just a placeholder value
                    url = url.replace('gdid', guarantorid);  // replace 'test' with the 'selected' value
                    window.location = url;
                    // swal("Error!", "Guarantor's ID did not match selected");
                    // return false
                }else{
                    swal("Error!", "Error typing");
                    $(".overlay").hide();
                    return false
                }

                //swal("Nice!", "You wrote: " + inputValue, "success");
            });
        });
    });

    
</script>
</html>

guarantordoc/templates/guarantordoc/detail.html
{% extends 'guarantordoc/base.html' %} {% block title %} Book Details {% endblock %} {% block body %}
{% include 'guarantordoc/header.html' %}

<div class="container">
    <div class="row">
        <div class="col-5">
            <img src="http://lib1.org{{ images }}" />
        </div>
        <div class="col-7">
            <table class="table table-striped table-condensed">
                <tr>
                    <td><h3>{{book_title |striptags|safe }}</h3></td>
                </tr>
                <tr>
                    <td>{{Author |striptags| safe }}</td>
                </tr>
                <tr>
                    <td>{{year |striptags|safe }}</td>
                </tr>
                <tr>
                    <td>{{isbn |striptags|safe}}</td>
                </tr>
                <tr>
                    <td>{{description |striptags |safe}}</td>
                </tr>
                <tr>
                    <td>
                        <a href="#" data-author="{{Author|striptags|safe }}" data-year="{{year|striptags|safe }}" data-book_title="{{book_title|striptags|safe}}" data-book_hash="{{md5|striptags|safe }}" id="donwloadbook" class="btn btn-primary donwloadbook">Download</a>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>
<script type='text/javascript'>
    $(function(){
        $('#donwloadbook').click(function(){
            var book_hash = $(this).data("book_hash");
            $.ajax({
                type: "GET",
                url: "/ajax/downloadbook",
                dataType: 'json',
                data:{
                    'book_id': book_hash,
                },
                success:function(response)
                {
                    console.log(response);
                }
            })
        })
    });
</script>
{% endblock %}

guarantordoc/templates/guarantordoc/header.html
<header>
    <div class="container">
        <nav class="navbar navbar-light bg-light">
            <a class="navbar-brand" href="{%url 'books:index' %}">Search Assistant</a>
            <form class="form-inline float-right" action="{% url 'books:search'%}" method="post">
                {% csrf_token %}
                <input class="form-control mr-sm-2 border-primary" type="search" placeholder="Search" id="search" name="search" aria-label="Search">
                <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
            </form>
            <div class="dropdown">
                <a class="btn border-primary dropdown-toggle" data-toggle="dropdown" id="dropdownProfile" href="#" role="button" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user"></i> {{ request.session.username }}</a>
                <div class="dropdown-menu" aria-labelledby="dropdownProfile">
                    <a class="dropdown-item" href="{% url 'accounts:logoutview' %}">Logout</a>
                </div>
            </div>
        </nav>
    </div>
</header>

guarantordoc/templates/guarantordoc/index.html
{% extends 'guarantordoc/base.html' %} {% block title %} Index {% endblock %}{% block body %}
{% include 'guarantordoc/header_home.html' %}
<div class="overlay">
    <div class="overlay-content">
        <div class="loader"></div>
        <div class="loading-text"><h3>Processing</h3></div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2 class="text-center mt-1">Guarantors</h2>
            <div class="row">
	            {% if exception %}
	                <div class="alert alert-danger col" role="alert">
	                    {{ exception }}
	                </div> 
	            {% endif %}
	            {% if messages %}
                    {% for message in messages %}
                        <alert {% if message.tags %} class="alert alert-danger col"{% endif %}>
                            {{ message }}
                        </alert>
                    {% endfor %}
                {% endif %}
	        </div>
            <table class="table table-striped" id="etable">
            	<thead class = "alert-success">
		            <tr>
		                <th>Driver Name</th>
		                <th>DRN</th>
		                <th>Guarantor Name</th>
		                <th>GuarantorId</th>
		                <th>Guarantor Phone</th>
		                <th>Guarantor Email</th>
		                <th></th>
		            </tr>
		        </thead>
		        <tbody>
		            {% for member in guarantorlist %}
		            <tr>
		                <td>{{ member.drivername }}</td>
		                <td>{{ member.drn }}</td>
		                <td>{{ member.firstname }} {{ member.lastname }}</td>
		                <td>{{ member.guarantorid }}</td>
		                <td>{{ member.phone }}</td>
		                <td>{{ member.email }}</td>
		                {% if member.requestid == null %}
						    <td><a href="#" class="btn btn-info sendBtn" id="sendBtn" data-guarantorid="{{member.id}}" data-guarantordrn="{{member.guarantorid}}">Send</a></td>
					  	{% else %}
					    	<td><a href="#" class="btn btn-success">Sent</a></td>
					  	{% endif %}
		            </tr>
		           {% endfor %}
		        </tbody>
		    </table>
        </div>
    </div>
</div>
<script type="text/javascript">
	

</script>
{% endblock %}
	        

guarantordoc/templates/guarantordoc/pdetail.html
{% extends 'books/base.html' %} {% block title %} Book Details {% endblock %} {% block body %}
{% include 'books/header.html' %}
<header>
    <div class="container">
        <nav class="navbar navbar-light bg-light">
            <a class="navbar-brand" href="{%url 'books:index' %}">Search</a>
            <form class="form-inline float-right" action="{% url 'books:search'%}" method="post">
                {% csrf_token %}
                <input class="form-control mr-sm-2 border-primary" type="search" placeholder="Search" id="search" name="search" aria-label="Search">
                <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
            </form>
        </nav>
    </div>
</header>

<div class="container">
    <div class="row">
        <div class="col-5">
            <img src="http://lib1.org{{ images }}" />
        </div>
        <div class="col-7">
            <table class="table table-striped table-condensed">
                <tr>
                    <td><h3>{{book_title |safe }}</h3></td>
                </tr>
                <tr>
                    <td>{{Author |safe }}</td>
                </tr>
                <tr>
                    <td>{{year |safe }}</td>
                </tr>
                <tr>
                    <td>{{isbn |safe}}</td>
                </tr>
                <tr>
                    <td>{{description |safe}}</td>
                </tr>
                <tr>
                    <td>
                        <a href="{{ downloadLink }}" class="btn btn-primary">Download</a>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>
{% endblock %}

guarantordoc/templates/guarantordoc/search.html
{% extends 'books/base.html' %} {% block title %} Search Result {% endblock %}{% block body %}
{% include 'books/header.html' %}

<div class="container">
    <ul class="nav nav-tabs nav-pills nav-fill" id="myTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="lda-book-tab" data-toggle="tab" href="#ldabooktab" role="tab" aria-controls="ldabok" aria-selected="false">LDA Videos Result</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " id="lda-video-tab" data-toggle="tab" href="#ldavideotab" role="tab" aria-controls="ldavideo" aria-selected="true">LDA Books Result</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Videos</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Books</a>
        </li>
    </ul>
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="ldabooktab" role="tabpanel" aria-labelledby="lda-book-tab">
            {% if lda_books %}

            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Document No</th>
                        <th>Dominant Topic</th>
                        <th>Topic Perc Contrib</th>
                        <th>Keywords</th>
                        <th>Text</th>
                    </tr>
                </thead>
                {% for dbook in lda_books %}
                <tr>
                    <td>
                        {{ dbook.Document_No }}
                    </td>
                    <td>{{ dbook.Dominant_Topic }}</td>
                    <td>
                        {{ dbook.Topic_Perc_Contrib }}
                    </td>
                    <td>
                        {{ dbook.Keywords }}
                    </td>
                    <td>
                        {{ dbook.Text }}
                    </td>
                </tr>
                {% endfor %}
            </table>
            {% else %}
                <h2> Lda returned empty</h2>
            {% endif %}
        </div>
        <div class="tab-pane fade" id="ldavideotab" role="tabpanel" aria-labelledby="lda-video-tab">
            {% if lda_videos %}
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Document No</th>
                        <th>Dominant Topic</th>
                        <th>Topic Perc Contrib</th>
                        <th>Keywords</th>
                        <th>Text</th>
                    </tr>
                </thead>
                {% for dvideo in lda_videos %}
                <tr>
                    <td>
                        {{ dvideo.Document_No }}
                    </td>
                    <td>{{ dvideo.Dominant_Topic }}</td>
                    <td>
                        {{ dvideo.Topic_Perc_Contrib }}
                    </td>
                    <td>
                        {{ dvideo.Keywords }}
                    </td>
                    <td>
                        {{ dvideo.Text }}
                    </td>
                </tr>
                {% endfor %}
            </table>
            {% else %}
                <h2> Lda returned empty</h2>
            {% endif %}
        </div>
        <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
            <div class="row mt-5">
            {% if videos %}
                {% for video in videos %}
                <div class="col-3 mt-3">
                  <div class="card">
                    <img src="{{ video.img_url }}" class="card-img-top" alt="{{ video.title }}">
                        <div class="card-body" style="height:200px;">
                            <h5 class="card-title"><a href="https://www.youtube.com/watch?v={{video.videoid}}" target="_blank">{{ video.title | title }}</a></h5>
                            <a href="https://www.youtube.com/watch?v={{video.videoid}}" data-videoid="{{video.videoid}}" data-video_title="{{video.title}}" class="btn btn-primary watchedVideo" id="" target="_blank">Watch</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            {% else %}
                <h2> No video was found</h2>
            {% endif %}
            </div>
        </div>
        <div class="tab-pane fade" id="home" role="tabpanel" aria-labelledby="home-tab">
            {% if data %}
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Author</th>
                        <th>Pages</th>
                        <th>File Size</th>
                        <th>Year of Publish</th>
                    </tr>
                </thead>

                {% for d in data %}

                <tr>
                    <td>
                        <a href="{{ d.durl }}" data-author="{{ d.author }}" data-year="{{ d.year }}" data-book_title="{{ d.title }}" data-book_hash="{{ d.durl }}" class="" target="_blank" >{{ d.title }} </a>
                    </td>
                    <td>{{ d.author }}</td>
                    <td>
                        {{ d.pages }}
                    </td>
                    <td>
                        {{ d.filesize }}
                    </td>
                    <td>
                        {{ d.year }}
                    </td>
                </tr>
                {% endfor %}
            </table>
            {% else %}
                <h2> No books was found</h2>
            {% endif %}
        </div>
        
    </div>
</div>

<script type='text/javascript'>
    $(function(){
        $('.bookpreview').click(function(){
            var author = $(this).data("author");
            var book_title = $(this).data("book_title");
            var year = $(this).data("year");
            var book_id = $(this).data("book_hash");
            $.ajax({
                type: "GET",
                url: '/ajax/downloadbook',
                dataType: 'json',
                data:{
                    'author': author,
                    'book_title': book_title,
                    'year': year,
                    'book_id': book_id,
                },
                success:function(response)
                {
                    console.log(response);
                }
            })
        })
    });

    $(function(){
        $('#watchedVideo').click(function(){
            var video_title = $(this).data("video_title");
            var videoid = $(this).data("videoid");
            $.ajax({
                type: "GET",
                url: '/ajax/watchedVideos',
                dataType: 'json',
                data:{
                    'videoid': videoid,
                    'video_title': video_title,
                },
                success:function(response)
                {
                    console.log(response);
                }
            })
        })
    });
</script>
{% endblock %}

guarantordoc/templates/guarantordoc/searchbar.html
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'books:index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#">Disabled</a>
                </li>
            </ul>
        </div>
    </nav>
</header>

guarantordoc/templates/guarantordoc/sendg.html
{% extends 'guarantordoc/base.html' %} {% block title %} Index {% endblock %}{% block body %}
{% include 'guarantordoc/header_home.html' %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="text-center mt-5">Keyword/Phrase</h1>
            {{ submitrespjson }}
        </div>
    </div>
    
</div>

{% endblock %}
	        