accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^$', views.loginview, name='login'),
    url(r'^accounts/login/$', views.loginview),
    url(r'^accounts/authview/$', views.authview, name='authview'),
    url(r'^accounts/logout/$', views.logoutview, name='logoutview'),
    url(r'^accounts/loggedin/$', views.loggedin, name='loggedin'),
    url(r'^accounts/invalid/$', views.invalid, name='invalid_login'),
    url(r'^accounts/register/$', views.register_user, name='register_user'),
    url(r'^accounts/register_success/$', views.register_success, name='register_success'),
]

moove_doc_signing/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^guarantordoc/', include('guarantordoc.urls')),
    url(r'^', include('guarantordoc.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^', include('accounts.urls')),
    # url(r'^search/', include('search.urls')),
    # url(r'^', include('search.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.
class AppUsers(models.Model):
    id = models.BigAutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    username = models.CharField(db_column='Username', max_length=255)  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=255)  # Field name made lowercase.
    supervisor = models.CharField(db_column='Supervisor', max_length=255)  # Field name made lowercase.
    forcechangepassword = models.IntegerField(db_column='ForceChangePassword')  # Field name made lowercase.
    password = models.CharField(db_column='Password', max_length=255)  # Field name made lowercase.
    canchangecompany = models.IntegerField(db_column='CanChangeCompany')  # Field name made lowercase.
    enabled = models.IntegerField(db_column='Enabled')  # Field name made lowercase.
    defaultcompany = models.CharField(db_column='DefaultCompany', max_length=10)  # Field name made lowercase.
    previouscompany = models.CharField(db_column='PreviousCompany', max_length=10)  # Field name made lowercase.
    loginfailcount = models.IntegerField(db_column='LoginFailCount')  # Field name made lowercase.
    branch = models.CharField(db_column='Branch', max_length=255)  # Field name made lowercase.
    createdby = models.CharField(db_column='CreatedBy', max_length=255)  # Field name made lowercase.
    createddatetime = models.DateTimeField(db_column='CreatedDateTime')  # Field name made lowercase.
    modifiedby = models.CharField(db_column='ModifiedBy', max_length=255)  # Field name made lowercase.
    modifieddatetime = models.DateTimeField(db_column='ModifiedDateTime')  # Field name made lowercase.
    company = models.CharField(db_column='Company', max_length=10)  # Field name made lowercase.
    recordversion = models.BigIntegerField(db_column='RecordVersion')  # Field name made lowercase.
    deleted = models.BigIntegerField(db_column='Deleted')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'app_users'
        unique_together = (('username', 'deleted'),)

accounts/forms.py
from django import forms
from .models import AppUsers
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

class MyRegistrationForm(UserCreationForm):

	username = forms.CharField(label='Enter Username', min_length=4, max_length=150)
	email = forms.EmailField(label='Enter email')
	password1 = forms.CharField(label='Enter password', widget=forms.PasswordInput)
	password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)

	class Meta:
		model = AppUsers
		fields = ('username', 'email', 'password1', 'password2')

	def clean_username(self):
		username = self.cleaned_data['username'].lower()
		r = User.objects.filter(username=username)
		if r.count():
			raise ValidationError("Username already exists")
		return username

	def clean_password2(self):
		password1 = self.cleaned_data.get('password1')
		password2 = self.cleaned_data.get('password2')
		if password1 and password2 and password1 != password2:
			raise ValidationError("Password don't match")
		return password2

	def clean_email(self):
		email = self.cleaned_data['email'].lower()
		r = User.objects.filter(email=email)
		if r.count():
			raise  ValidationError("Email already exists")
		return email

	def save(self, commit=True):
		user = super(UserCreationForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		user.username = self.cleaned_data['username']
		user.set_password(self.cleaned_data['password1'])

		if commit:
			user.save()

		return user

accounts/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404, HttpResponse
from accounts.forms import MyRegistrationForm
from django.template.context_processors import csrf
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.conf.urls import url
from datetime import datetime, time, timedelta
from django.utils import timezone
from .models import AppUsers
# from pylibgen import Library

import requests
import re

def loginview(request):
    context = {
        'title': 'title',
    }
    return render(request, 'accounts/login.html', context) 
    # return HttpResponse(url)




def authview(request):

    try:
    	username = request.POST.get('username', '')
    	password = request.POST.get('password', '')
    	user = AppUsers.objects.get(username=username)
    	request.session['username'] = username
    	return HttpResponseRedirect('/guarantorslist/')
    except requests.exceptions.ConnectionError:
        connection_status = "Connection refused"
        context = {
            'exception': connection_status,
        }
        # return HttpResponse(requests.exceptions)
        messages.warning(request, connection_status)
        return HttpResponseRedirect('/')
    except AssertionError as error:
        # Output expected AssertionErrors.
        # Logging.log_exception(error)
        messages.warning(request, "Username or password incorrect")
        return HttpResponseRedirect('/')
    except Exception as exception:
        # Output unexpected Exceptions.
        # Logging.log_exception(exception, False)
        context = {
            'exception': "Request Not found",
        }
        # return HttpResponse(exception)
        messages.warning(request, "Username or password incorrect")
        return HttpResponseRedirect('/')


def invalid(request):
    context = {
        'title': 'title',
    }
    return render(request, 'accounts/invalid.html', context)
    # return HttpResponse(url)


@login_required
def loggedin(request):
    context = {
        'title': 'title',
    }
    return render(request, 'accounts/dashboard.html', context)
    # return HttpResponse(url)


def logoutview(request):
    # logout(request)
    del request.session['username']
    messages.warning(request, 'Successfully Looged Out')
    return HttpResponseRedirect('/')
    


def register_user(request):
	if request.method == 'POST':
		form = MyRegistrationForm(request.POST)
		if form.is_valid():
			form.save()
			messages.success(request, 'Registration Successful. Kindly login to proceed')
			return HttpResponseRedirect('/accounts/login')
	else:
		form = MyRegistrationForm()

	args = {}
	args.update(csrf(request))
	context = {
		'form': form
	}
	return render(request, 'accounts/register.html', context)
	# return HttpResponse(form)


def register_success(request):
	context = {
		'success': 'User created successfully',
	}
	return render(request, 'accounts/register_success.html', context)
	# return HttpResponse(url)

accounts/templates/accounts/register.html
{% extends 'guarantordoc/base.html' %} {% block title %} Login {% endblock %}{% block body %}

<div class="container text-center">
    <div class="row mt-5">
        <div class="col-md-4 offset-md-4 mt-5">
            <h2 class="text-center mt-5">New User</h2>
            <form action="{% url 'accounts:register_user'%}" method="post" class="mt-5 text-left">
                {% csrf_token %}
                <div class="row">
                    {% if exception %}
                        <div class="alert alert-danger col" role="alert">
                            {{ exception }}
                        </div> 
                    {% endif %}

                </div>
                <div class="form-group">
                    {{ form.username.errors }}
                    <label for="exampleInputEmail1">Username</label>
                    <input type="text" id="username" name="username" value="" class="form-control border-primary" required="" />
                </div>
                <div class="form-group">
                    {{ form.email.errors }}
                    <label for="exampleInputEmail1">Email Address</label>
                    <input type="text" id="username" name="email" value="" class="form-control border-primary" required="" />
                </div>
                <div class="form-group">
                    {{ form.password1.errors }}
                    <label for="exampleInputPassword1">Password</label>
                    <input type="password" id="password1" name="password1" value="" class="form-control border-primary" required="" />
                </div>
                <div class="form-group">
                    {{ form.password2.errors }}
                    <label for="exampleInputPassword1">Password</label>
                    <input type="password" id="password2" name="password2" value="" class="form-control border-primary" required="" />
                </div>
                <div class="row mt-3">
                    <div class="col text-left">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <button type="reset" class="btn btn-danger">Reset</button>
                    </div>
                </div>
                <p class="mt-3"><a href="{% url 'accounts:register_user' %}">Already Registered</a></p>
            </form>
        </div>
    </div>
</div>

{% endblock %}